"""
sql_safety.py

Deterministic SQL safety checks for AI-generated queries before preview or agent
execution. The validator is dependency-free so it works inside the desktop sidecar.
"""

from dataclasses import asdict, dataclass, field
import re
from typing import List, Optional


READ_ONLY_STARTERS = {"select", "with", "show", "describe", "desc", "explain", "pragma"}
WRITE_STARTERS = {
    "alter",
    "analyze",
    "attach",
    "call",
    "comment",
    "copy",
    "create",
    "delete",
    "detach",
    "drop",
    "execute",
    "grant",
    "insert",
    "merge",
    "replace",
    "revoke",
    "set",
    "truncate",
    "update",
    "vacuum",
}
UNSAFE_ANYWHERE = {
    "alter",
    "attach",
    "create",
    "delete",
    "detach",
    "drop",
    "grant",
    "insert",
    "merge",
    "replace",
    "revoke",
    "truncate",
    "update",
}
LIMIT_PATTERN = re.compile(r"\blimit\s+\d+\b", re.IGNORECASE)
OFFSET_ONLY_PATTERN = re.compile(r"\boffset\s+\d+\b", re.IGNORECASE)
SELECT_INTO_PATTERN = re.compile(r"\bselect\b[\s\S]+\binto\b", re.IGNORECASE)
SLEEP_PATTERN = re.compile(r"\b(pg_sleep|sleep|benchmark)\s*\(", re.IGNORECASE)


@dataclass(frozen=True)
class SqlSafetyReport:
    """Serializable validation report for SQL generated by AI features."""

    isAllowed: bool
    sanitizedSql: str
    statementType: str
    riskLevel: str
    requiresConfirmation: bool
    warnings: List[str] = field(default_factory=list)
    blockedReason: str = ""
    limitApplied: bool = False

    def to_dict(self) -> dict:
        return asdict(self)


class SqlSafetyValidator:
    """Validates and lightly normalizes SQL before AI-triggered execution."""

    def validate(
        self,
        sql: str,
        dialect: Optional[str] = None,
        allow_write: bool = False,
        max_preview_rows: int = 500,
    ) -> SqlSafetyReport:
        original_sql = str(sql or "").strip()
        max_preview_rows = max(1, min(int(max_preview_rows or 500), 5000))
        if not original_sql:
            return self._blocked("", "empty", "SQL is empty.")

        scrubbed = self._strip_comments_and_literals(original_sql)
        statements = [part.strip() for part in self._split_statements(scrubbed) if part.strip()]
        raw_statements = [part.strip() for part in self._split_statements(original_sql) if part.strip()]
        if len(statements) != 1 or len(raw_statements) != 1:
            return self._blocked(original_sql, "multiple", "Multiple SQL statements are not allowed for AI execution.")

        statement_type = self._first_keyword(statements[0])
        if not statement_type:
            return self._blocked(original_sql, "unknown", "Could not determine the SQL statement type.")

        lowered_tokens = set(re.findall(r"[a-z_]+", statements[0].lower()))
        has_write_keyword = bool(UNSAFE_ANYWHERE.intersection(lowered_tokens))
        if statement_type in WRITE_STARTERS or (has_write_keyword and not allow_write):
            return SqlSafetyReport(
                isAllowed=False,
                sanitizedSql=original_sql,
                statementType=statement_type,
                riskLevel="high",
                requiresConfirmation=True,
                warnings=["write_or_ddl_detected"],
                blockedReason="AI execution is read-only by default. Review and run this query manually if it is intentional.",
            )

        if statement_type == "select" and SELECT_INTO_PATTERN.search(statements[0]):
            return self._blocked(original_sql, statement_type, "SELECT INTO can create tables and is blocked for AI preview.")

        if SLEEP_PATTERN.search(statements[0]):
            return self._blocked(original_sql, statement_type, "Delay and benchmark functions are blocked for AI preview.")

        if statement_type not in READ_ONLY_STARTERS:
            return self._blocked(original_sql, statement_type, f"Unsupported SQL statement type: {statement_type}.")

        sanitized_sql, limit_applied = self._apply_preview_limit(original_sql, statement_type, dialect, max_preview_rows)
        warnings = []
        if limit_applied:
            warnings.append(f"limit_applied:{max_preview_rows}")
        if statement_type in {"explain", "pragma", "show", "describe", "desc"}:
            warnings.append("metadata_statement")

        return SqlSafetyReport(
            isAllowed=True,
            sanitizedSql=sanitized_sql,
            statementType=statement_type,
            riskLevel="low" if not warnings else "medium",
            requiresConfirmation=False,
            warnings=warnings,
            limitApplied=limit_applied,
        )

    def _apply_preview_limit(
        self,
        sql: str,
        statement_type: str,
        dialect: Optional[str],
        max_preview_rows: int,
    ) -> tuple[str, bool]:
        if statement_type not in {"select", "with"}:
            return sql, False
        if LIMIT_PATTERN.search(sql) or OFFSET_ONLY_PATTERN.search(sql):
            return sql, False
        normalized_dialect = str(dialect or "").lower()
        if normalized_dialect in {"oracle", "mssql", "sqlserver"}:
            return sql, False

        trimmed = sql.rstrip().rstrip(";")
        return f"{trimmed}\nLIMIT {max_preview_rows};", True

    def _first_keyword(self, sql: str) -> str:
        match = re.search(r"[a-zA-Z_]+", sql)
        return match.group(0).lower() if match else ""

    def _blocked(self, sql: str, statement_type: str, reason: str) -> SqlSafetyReport:
        return SqlSafetyReport(
            isAllowed=False,
            sanitizedSql=sql,
            statementType=statement_type,
            riskLevel="high",
            requiresConfirmation=True,
            blockedReason=reason,
        )

    def _split_statements(self, sql: str) -> List[str]:
        statements: List[str] = []
        current: List[str] = []
        quote = ""
        index = 0
        while index < len(sql):
            char = sql[index]
            current.append(char)
            if quote:
                if char == quote:
                    if index + 1 < len(sql) and sql[index + 1] == quote:
                        current.append(sql[index + 1])
                        index += 1
                    else:
                        quote = ""
            elif char in {"'", '"', "`"}:
                quote = char
            elif char == ";":
                statements.append("".join(current[:-1]).strip())
                current = []
            index += 1
        if current:
            statements.append("".join(current).strip())
        return statements

    def _strip_comments_and_literals(self, sql: str) -> str:
        output: List[str] = []
        quote = ""
        index = 0
        while index < len(sql):
            char = sql[index]
            next_char = sql[index + 1] if index + 1 < len(sql) else ""
            if quote:
                output.append(" ")
                if char == quote:
                    if next_char == quote:
                        output.append(" ")
                        index += 1
                    else:
                        quote = ""
            elif char in {"'", '"', "`"}:
                quote = char
                output.append(" ")
            elif char == "-" and next_char == "-":
                while index < len(sql) and sql[index] not in "\r\n":
                    output.append(" ")
                    index += 1
                continue
            elif char == "/" and next_char == "*":
                output.extend("  ")
                index += 2
                while index < len(sql) - 1 and not (sql[index] == "*" and sql[index + 1] == "/"):
                    output.append(" ")
                    index += 1
                output.extend("  ")
                index += 1
            else:
                output.append(char)
            index += 1
        return "".join(output)


sql_safety_validator = SqlSafetyValidator()
