import { describe, expect, it } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import {
  parseVersionFromEnv,
  validateSemver,
  syncVersion,
  checkVersion,
  type TargetResult,
} from "./sync-version";

describe("Version validation and parsing", () => {
  it("parses valid QURIODB_VERSION from env string", () => {
    const envContent = "FOO=bar\nQURIODB_VERSION=1.2.3\nBAZ=qux";
    expect(parseVersionFromEnv(envContent)).toBe("1.2.3");
  });

  it("handles whitespace and quotes in env file", () => {
    expect(parseVersionFromEnv('QURIODB_VERSION="1.2.3"')).toBe("1.2.3");
    expect(parseVersionFromEnv("QURIODB_VERSION='1.2.3'")).toBe("1.2.3");
    expect(parseVersionFromEnv("  QURIODB_VERSION = 1.2.3  ")).toBe("1.2.3");
  });

  it("throws error when QURIODB_VERSION is missing", () => {
    expect(() => parseVersionFromEnv("FOO=bar")).toThrow(
      "Missing QURIODB_VERSION in environment configuration",
    );
  });

  it("throws error on malformed semver 1.2 or prefixed v1.2.3", () => {
    expect(() => validateSemver("1.2")).toThrow("Invalid semantic version: '1.2'");
    expect(() => validateSemver("v1.2.3")).toThrow("Invalid semantic version: 'v1.2.3'");
    expect(() => validateSemver("1.2.3.4")).toThrow("Invalid semantic version: '1.2.3.4'");
    expect(() => validateSemver("latest")).toThrow("Invalid semantic version: 'latest'");
    expect(() => validateSemver("")).toThrow("Invalid semantic version: ''");
  });

  it("validates standard semantic versions", () => {
    expect(validateSemver("0.1.0")).toBe("0.1.0");
    expect(validateSemver("1.2.3")).toBe("1.2.3");
    expect(validateSemver("1.0.0-alpha.1")).toBe("1.0.0-alpha.1");
    expect(validateSemver("2.0.0-rc.2+build.123")).toBe("2.0.0-rc.2+build.123");
  });
});

describe("Version sync and check against fixtures", () => {
  const createFixtureWorkspace = (initialVersion = "0.1.0") => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "quriodb-version-test-"));

    const desktopPackageJsonRaw = `{
  "name": "desktop",
  "version": "${initialVersion}",
  "description": "Desktop app for QurioDB",
  "main": "main.js",
  "author": "QurioDB Team",
  "private": true,
  "scripts": {
    "dev": "tauri dev",
    "build": "tauri build",
    "tauri": "tauri",
    "test": "vitest run"
  },
  "dependencies": {
  },
  "devDependencies": {
    "@tauri-apps/cli": "^2.1.0",
    "vitest": "^4.0.18"
  }
}
`;

    const tauriConfJsonRaw = `{
  "$schema": "../node_modules/@tauri-apps/cli/config.schema.json",
  "productName": "QurioDB",
  "version": "${initialVersion}",
  "identifier": "com.quriodb.app",
  "build": {
    "frontendDist": "../../web/dist"
  }
}
`;

    const cargoToml = `[package]
name = "quriodb-desktop"
version = "${initialVersion}"
description = "QurioDB Desktop"

[dependencies]
rand = "0.8"
`;

    const cargoLock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "other-pkg"
version = "0.1.0"

[[package]]
name = "quriodb-desktop"
version = "${initialVersion}"
dependencies = [
 "rand",
]

[[package]]
name = "another-pkg"
version = "0.1.0"
`;

    const rootReadme = `# QurioDB

- [Download Windows Installer (v${initialVersion})](https://github.com/trungvinh2102/QurioDB/releases/download/v${initialVersion}/QurioDB_${initialVersion}_x64_en-US.msi)
- [Download Windows Setup (v${initialVersion})](https://github.com/trungvinh2102/QurioDB/releases/download/v${initialVersion}/QurioDB_${initialVersion}_x64-setup.exe)
- [Download Linux Package (v${initialVersion})](https://github.com/trungvinh2102/QurioDB/releases/download/v${initialVersion}/QurioDB_${initialVersion}_amd64.deb)

QurioDB - v${initialVersion}
`;

    const desktopReadme = `# QurioDB - Desktop Build Guide

_QurioDB Team - v${initialVersion}_
`;

    const sentinelContent = "UNTOUCHED_SENTINEL_DATA_12345";

    fs.mkdirSync(path.join(tempDir, "apps/desktop/src-tauri"), { recursive: true });
    fs.mkdirSync(path.join(tempDir, "unrelated-dir"), { recursive: true });

    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/package.json"),
      desktopPackageJsonRaw,
    );
    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/src-tauri/tauri.conf.json"),
      tauriConfJsonRaw,
    );
    fs.writeFileSync(path.join(tempDir, "apps/desktop/src-tauri/Cargo.toml"), cargoToml);
    fs.writeFileSync(path.join(tempDir, "apps/desktop/src-tauri/Cargo.lock"), cargoLock);
    fs.writeFileSync(path.join(tempDir, "README.md"), rootReadme);
    fs.writeFileSync(path.join(tempDir, "apps/desktop/README.md"), desktopReadme);
    fs.writeFileSync(path.join(tempDir, "unrelated-dir/sentinel.txt"), sentinelContent);

    return { tempDir, desktopPackageJsonRaw, tauriConfJsonRaw, sentinelContent };
  };

  it("syncs target version 1.2.3, preserves byte formatting and leaves sentinel untouched", () => {
    const { tempDir: workspace, desktopPackageJsonRaw, sentinelContent } = createFixtureWorkspace("0.1.0");
    const results = syncVersion("1.2.3", workspace);

    expect(results.every((r) => r.updated)).toBe(true);

    const desktopPkgContent = fs.readFileSync(
      path.join(workspace, "apps/desktop/package.json"),
      "utf-8",
    );
    const expectedDesktopPkg = desktopPackageJsonRaw.replace(
      '"version": "0.1.0"',
      '"version": "1.2.3"',
    );
    expect(desktopPkgContent).toBe(expectedDesktopPkg);
    expect(desktopPkgContent).toContain('"dependencies": {\n  }');

    const sentinelActual = fs.readFileSync(
      path.join(workspace, "unrelated-dir/sentinel.txt"),
      "utf-8",
    );
    expect(sentinelActual).toBe(sentinelContent);

    const cargoToml = fs.readFileSync(
      path.join(workspace, "apps/desktop/src-tauri/Cargo.toml"),
      "utf-8",
    );
    expect(cargoToml).toContain('version = "1.2.3"');

    const cargoLock = fs.readFileSync(
      path.join(workspace, "apps/desktop/src-tauri/Cargo.lock"),
      "utf-8",
    );
    expect(cargoLock).toContain('name = "other-pkg"\nversion = "0.1.0"');
    expect(cargoLock).toContain('name = "another-pkg"\nversion = "0.1.0"');
    expect(cargoLock).toContain('name = "quriodb-desktop"\nversion = "1.2.3"');

    const rootReadme = fs.readFileSync(path.join(workspace, "README.md"), "utf-8");
    expect(rootReadme).toContain("Download Windows Installer (v1.2.3)");
    expect(rootReadme).toContain("QurioDB_1.2.3_x64_en-US.msi");
    expect(rootReadme).toContain("QurioDB_1.2.3_x64-setup.exe");
    expect(rootReadme).toContain("QurioDB_1.2.3_amd64.deb");
    expect(rootReadme).toContain("QurioDB - v1.2.3");

    const desktopReadme = fs.readFileSync(
      path.join(workspace, "apps/desktop/README.md"),
      "utf-8",
    );
    expect(desktopReadme).toContain("_QurioDB Team - v1.2.3_");

    fs.rmSync(workspace, { recursive: true, force: true });
  });

  it("checkVersion detects stale files and passes when in sync", () => {
    const { tempDir: workspace } = createFixtureWorkspace("0.1.0");

    const staleResults = checkVersion("1.2.3", workspace);
    const staleFiles = staleResults.filter((r) => !r.inSync).map((r) => r.path);
    expect(staleFiles).toEqual([
      "apps/desktop/package.json",
      "apps/desktop/src-tauri/tauri.conf.json",
      "apps/desktop/src-tauri/Cargo.toml",
      "apps/desktop/src-tauri/Cargo.lock",
      "README.md",
      "apps/desktop/README.md",
    ]);

    syncVersion("1.2.3", workspace);
    const syncedResults = checkVersion("1.2.3", workspace);
    expect(syncedResults.every((r) => r.inSync)).toBe(true);

    fs.rmSync(workspace, { recursive: true, force: true });
  });
});

describe("CLI Boundary and Subprocess Execution", () => {
  const syncScriptPath = path.join(process.cwd(), "scripts/sync-version.ts");

  it("CLI exits 1 with error when .env is missing in fixture root", () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "quriodb-cli-noenv-"));
    const proc = Bun.spawnSync(["bun", syncScriptPath], {
      cwd: tempDir,
    });
    expect(proc.exitCode).toBe(1);
    const stderr = proc.stderr.toString();
    expect(stderr).toContain("Canonical environment file not found");
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it("CLI exits 1 when QURIODB_VERSION is malformed (1.2 or v1.2.3)", () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "quriodb-cli-malformed-"));
    fs.writeFileSync(path.join(tempDir, ".env"), "QURIODB_VERSION=1.2\n");
    const proc1 = Bun.spawnSync(["bun", syncScriptPath], {
      cwd: tempDir,
    });
    expect(proc1.exitCode).toBe(1);
    expect(proc1.stderr.toString()).toContain("Invalid semantic version: '1.2'");

    fs.writeFileSync(path.join(tempDir, ".env"), "QURIODB_VERSION=v1.2.3\n");
    const proc2 = Bun.spawnSync(["bun", syncScriptPath], {
      cwd: tempDir,
    });
    expect(proc2.exitCode).toBe(1);
    expect(proc2.stderr.toString()).toContain("Invalid semantic version: 'v1.2.3'");
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it("CLI --check prints every stale path and exits 1 on mismatch", () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "quriodb-cli-stale-"));
    fs.writeFileSync(path.join(tempDir, ".env"), "QURIODB_VERSION=2.0.0\n");

    fs.mkdirSync(path.join(tempDir, "apps/desktop/src-tauri"), { recursive: true });
    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/package.json"),
      JSON.stringify({ name: "desktop", version: "0.1.0" }, null, 2),
    );
    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/src-tauri/tauri.conf.json"),
      JSON.stringify({ productName: "QurioDB", version: "0.1.0" }, null, 2),
    );
    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/src-tauri/Cargo.toml"),
      '[package]\nname = "quriodb-desktop"\nversion = "0.1.0"\n',
    );
    fs.writeFileSync(
      path.join(tempDir, "apps/desktop/src-tauri/Cargo.lock"),
      '[[package]]\nname = "quriodb-desktop"\nversion = "0.1.0"\n',
    );
    fs.writeFileSync(
      path.join(tempDir, "README.md"),
      "- [Download Windows Installer (v0.1.0)](https://github.com/trungvinh2102/QurioDB/releases/download/v0.1.0/QurioDB_0.1.0_x64_en-US.msi)\n- [Download Windows Setup (v0.1.0)](https://github.com/trungvinh2102/QurioDB/releases/download/v0.1.0/QurioDB_0.1.0_x64-setup.exe)\n- [Download Linux Package (v0.1.0)](https://github.com/trungvinh2102/QurioDB/releases/download/v0.1.0/QurioDB_0.1.0_amd64.deb)\nQurioDB - v0.1.0\n",
    );
    fs.writeFileSync(path.join(tempDir, "apps/desktop/README.md"), "_QurioDB Team - v0.1.0_\n");

    const checkProc = Bun.spawnSync(["bun", syncScriptPath, "--check"], {
      cwd: tempDir,
    });
    expect(checkProc.exitCode).toBe(1);
    const stderr = checkProc.stderr.toString();
    expect(stderr).toContain("Version mismatch detected! Canonical QURIODB_VERSION=2.0.0");
    expect(stderr).toContain("apps/desktop/package.json");
    expect(stderr).toContain("apps/desktop/src-tauri/tauri.conf.json");
    expect(stderr).toContain("apps/desktop/src-tauri/Cargo.toml");
    expect(stderr).toContain("apps/desktop/src-tauri/Cargo.lock");
    expect(stderr).toContain("README.md");
    expect(stderr).toContain("apps/desktop/README.md");

    const syncProc = Bun.spawnSync(["bun", syncScriptPath], {
      cwd: tempDir,
    });
    expect(syncProc.exitCode).toBe(0);

    const checkProcAfter = Bun.spawnSync(["bun", syncScriptPath, "--check"], {
      cwd: tempDir,
    });
    expect(checkProcAfter.exitCode).toBe(0);
    expect(checkProcAfter.stdout.toString()).toContain("All managed targets match QURIODB_VERSION=2.0.0");

    fs.rmSync(tempDir, { recursive: true, force: true });
  });
});

describe("Root package.json desktop scripts validation", () => {
  it("verifies package.json desktop commands include bun run version:sync && prefix", () => {
    const rootPkg = JSON.parse(
      fs.readFileSync(path.join(process.cwd(), "package.json"), "utf-8"),
    );
    const scripts = rootPkg.scripts || {};

    const requiredCommands = [
      "desktop:build",
      "desktop:sidecar:linux",
      "desktop:build:linux",
      "desktop:dev:linux",
      "desktop:dev:windows",
    ];

    for (const cmd of requiredCommands) {
      expect(scripts[cmd]).toBeDefined();
      expect(scripts[cmd].startsWith("bun run version:sync &&")).toBe(true);
    }
  });
});
